# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        swift-version: ["5.9", "6.0"]
        include:
          - swift-version: "5.9"
            runner: macos-latest
          - swift-version: "6.0"
            runner: macos-14

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
